export const USER_TOKEN = "TOKEN_USER";
export const LOGIN_URL = "https://myinno.myglu.com/oxauth/restv1/token";
export const USER_SIGNUP = "USER_SIGNUP";
export const GET_VALIDATE="GET_VALIDATE";
export const GET_EMAIL_VALIDATE="GET_EMAIL_VALIDATE";
export const GET_EMAIL_URL="http://192.168.208.233:80/jemstepUser/user/emailOtpUser"
// export const GET_EMAIL_URL="https://myinno.myglu.com/identity/restv1/scim/v2/Users/"
// export const USER_ERROR="USER_ERROR";
export const GET_USER="GET_USER";
export const GET_USERLOGIN_URL = "https://myinno.myglu.com/oxauth/restv1/token";
// export const SIGNUP_URL = "https://myinno.myglu.com/identity/restv1/scim/v2/Users";
// export const SIGNUP_URL="https://myinno.myglu.com/oxauth/restv1/register"
export const SIGNUP_URL = "http://mahesh.myglu.com/jemstepUser/user/createUser";
export const GETUSERS_URL = "http://192.168.208.233/jemstepUser/user/retrievUser";

// export const SIGNUP_URL = "http://192.168.204.42:8081/jemstepUser/user/createUser";
// export const ALERT_CONFIG = { position: 'top-right', effect: 'bouncyflip'};
// export const ALL_USERS = "ALL_USERS";
// export const ALL_USERS_URL = "http://localhost:3000/users/getAllUserss